name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod tidy
        working-directory: ../.. # Root of the project relative to .github/workflows/

      - name: Run tests
        run: go test ./... -v
        working-directory: ../.. # Root of the project relative to .github/workflows/

      - name: Lint the code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
        working-directory: ../.. # Root of the project relative to .github/workflows/

      - name: Deploy to Staging
        if: success()
        run: |
          echo "Deploying to staging environment..."
        working-directory: ../.. # Root of the project relative to .github/workflows/
