name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code using the latest version compatible with Node.js 16
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node.js 16 compatibility
        with:
          fetch-depth: 0

      # Step 2: Set up Go environment using the latest version compatible with Node.js 16
      - name: Set up Go
        uses: actions/setup-go@v4  # Updated to v4 for Node.js 16 compatibility
        with:
          go-version: '1.18'  # Use the version you updated in go.mod

      # Step 3: Debug - Show current working directory and confirm go.mod is present
      - name: Debug - Show Current Working Directory and Files
        run: |
          echo "Checking working directory and file structure:"
          pwd
          ls -la
          find . -name "go.mod" || echo "go.mod not found!"
        working-directory: ./

      # Step 4: Install dependencies using go.mod
      - name: Install dependencies
        run: go mod tidy
        working-directory: ./

      # Step 5: Run tests
      - name: Run tests
        run: go test ./... -v
        working-directory: ./

      # Step 6: Install a compatible version of golangci-lint
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
        working-directory: ./

      # Step 7: Lint the code
      - name: Lint the code
        run: golangci-lint run
        working-directory: ./
