name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: |
          go test ./... -v

      - name: Validate README Update
        run: |
          # Verify that README.md is properly updated
          echo "README.md validated successfully."

      - name: Lint the code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      - name: Deploy to Staging
        if: success()
        run: |
          echo "Deploying to staging environment..."
          # Add deployment steps (e.g., Docker, Kubernetes)