name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Full history

      # Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      # Debug step to verify the directory and check for go.mod
      - name: Debug - Verify go.mod Location
        run: |
          pwd
          ls -la
          cat go.mod || echo "go.mod not found!"  # Attempt to print go.mod contents
        working-directory: ./  # Set this to your project's root

      # Install dependencies using go.mod
      - name: Install dependencies
        run: go mod tidy
        working-directory: ./  # Ensure correct working directory

      # Run tests
      - name: Run tests
        run: go test ./... -v
        working-directory: ./  # Ensure correct working directory

      # Lint the code
      - name: Lint the code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
        working-directory: ./  # Ensure correct working directory
