name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      # Step 3: Debug step to confirm the working directory and list files
      - name: Debug - Show Current Working Directory and Files
        run: |
          pwd
          ls -la
        working-directory: ./  # Root directory where go.mod is located

      # Step 4: Install dependencies using go.mod
      - name: Install dependencies
        run: go mod tidy
        working-directory: ./  # Ensure the command runs in the root directory

      # Step 5: Run tests
      - name: Run tests
        run: go test ./... -v
        working-directory: ./  # Ensure tests run in the correct context

      # Step 6: Lint the code using golangci-lint
      - name: Lint the code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
        working-directory: ./  # Run linting in the correct directory
