name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      # Verify the current working directory and the presence of go.mod
      - name: Verify go.mod location
        run: |
          pwd
          ls -la
        working-directory: ./  # Adjust this if go.mod is not at the root

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy
        working-directory: ./  # Adjust this if go.mod is not at the root

      # Run tests
      - name: Run tests
        run: go test ./... -v
        working-directory: ./  # Adjust this if go.mod is not at the root

      # Lint the code
      - name: Lint the code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
        working-directory: ./  # Adjust this if go.mod is not at the root
