name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # Use the version you updated in go.mod

      - name: Debug - Show Current Working Directory and Files
        run: |
          echo "Checking working directory and file structure:"
          pwd
          ls -la
          find . -name "go.mod" || echo "go.mod not found!"
        working-directory: ./

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./

      - name: Run tests
        run: go test ./... -v
        working-directory: ./

      # Install a compatible version of golangci-lint
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
        working-directory: ./

      - name: Lint the code
        run: golangci-lint run
        working-directory: ./
